/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INITCOMPONENT;

import COMPONENT.SCROLLBAR.ScrollBarMod;
import Event.EventMenu;
import SWINGCOMPONENT.ButtonMenu;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author ACER
 */
public class SIDEBARPANEL extends javax.swing.JPanel {

    /**
     * Creates new form SIEBARPANEL
     */
    private EventMenu event;
    public SIDEBARPANEL() {
        initComponents();
         setOpaque(false);
        ScrollBarMod sb = new ScrollBarMod();
        
        sb.setForeground(new Color(130, 130, 130, 100));
        jScrollPane1.setVerticalScrollBar(sb);
        panelMenu.setLayout(new MigLayout("wrap, fillx, inset 3", "[fill]", "[]0[]"));
    }
//     String [] dataMenu = new String[100];
     public void initMenu(EventMenu event  ) {
         this.event = event;

         addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/rosterlogo.png")),"Roster" , 0);
        addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/studentlogo.png")), "Siswa", 1);
          addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/staflogo.png")), "Pegawai", 2);
          addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/studilogo.png")), "Bidang Studi", 3);
            addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/reportlogo.png")), "Laporan", 4);
           addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/logoutlogo.png")), "Log Out", 5);

    }
     
          public void initMenu2(EventMenu event  ) {
         this.event = event;

        addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/classlogo.png")),"Kelas" , 0);
        addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/quizlogo.png")), "Kuis", 1);
        addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/logoutlogo.png")), "Keluar", 2);

//          addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/staflogo.png")), "Pegawai", 2);
//          addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/studilogo.png")), "Bidang Studi", 3);
//            addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/reportlogo.png")), "Laporan", 4);
//           addMenu(new ImageIcon(getClass().getResource("/COMPONENT/IMAGEREPOSITORY/ICONMENU/logoutlogo.png")), "Log Out", 5);


    }
     
     private void addMenu(Icon icon, String text, int index) {
        ButtonMenu menu = new ButtonMenu();
        menu.setIcon(icon);
        menu.setText("  " + text);
        panelMenu.add(menu);
        menu.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.selected(index);
                setSelected(menu);
            }
        });
    }
        private void addEmpty() {
        panelMenu.add(new JLabel(), "push");
    }
     
          private void setSelected(ButtonMenu menu) {
        for (Component com : panelMenu.getComponents()) {
            if (com instanceof ButtonMenu) {
                ButtonMenu b = (ButtonMenu) com;
                b.setSelected(false);
            }
        }
        menu.setSelected(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        panelMenu.setBackground(new java.awt.Color(0, 153, 153));
        panelMenu.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(panelMenu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
