/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeRun;

import COMPONENT.LOGINPANEL;
import Connection.Koneksi;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class LOGINRUN extends javax.swing.JFrame {

    /**
     * Creates new form LOGINRUN
     */
    LOGINPANEL lg ;
    LOGINPANEL lg2 ;
    public Connection con ;
    private int dare ;
    public int getDare(){
        return  dare ;
    }
    private void setDare(int n){
        dare = n ;
    }
    public LOGINRUN() {
       setUndecorated(true);
       Koneksi k = new Koneksi();
       k.Config();
       this.con = k.con ;
       initComponents();
       setLocationRelativeTo(null);
//       this.setComponentZOrder(panelGeser, 0);
       // panelinit.setVisible(false);
       LOGINPANEL lg = new LOGINPANEL(this);
       lg.setTitle("ADMIN LOGIN");
       lg.setBounds(450, 25,290, 383);
       lg.setVisible(false);
       lg.NoChanges();
       panelRound3.add(lg);
       this.lg= lg ;
       LOGINPANEL lg2 = new LOGINPANEL(this);
       
       lg2.setTitle("GURU LOGIN");
       lg2.setBounds(50, 25, 290, 383);
       panelRound3.add(lg2);
       lg2.setVisible(false);
       this.lg2 = lg2 ;
     
    }
    
    public void keep(){
           panelGeser.setBounds(0 , 0,394 , 445);
    }
    int nStatus = 0 ;
    public int getstatus(){
        return nStatus ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound4 = new test.PanelRound();
        panelRound5 = new test.PanelRound();
        panelRound1 = new test.PanelRound();
        panelRound2 = new test.PanelRound();
        panelRound3 = new test.PanelRound();
        panelGeser = new test.PanelRound();
        button1 = new button.Button();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRound5.setBackground(new java.awt.Color(0, 0, 0));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new java.awt.CardLayout());

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(50);
        panelRound3.setRoundBottomRight(50);
        panelRound3.setRoundTopLeft(50);
        panelRound3.setRoundTopRight(50);

        panelGeser.setBackground(new java.awt.Color(0, 153, 153));
        panelGeser.setRoundBottomLeft(50);
        panelGeser.setRoundBottomRight(50);
        panelGeser.setRoundTopLeft(50);
        panelGeser.setRoundTopRight(50);
        panelGeser.setLayout(null);

        button1.setText("LOGIN SEBAGAI GURU");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panelGeser.add(button1);
        button1.setBounds(140, 380, 150, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive\\Pictures\\igda-removebg-preview.png")); // NOI18N
        panelGeser.add(jLabel1);
        jLabel1.setBounds(110, 50, 180, 180);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addGap(0, 394, Short.MAX_VALUE)
                .addComponent(panelGeser, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        panelRound2.add(panelRound3, "card2");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean isGeser = false ;
    public int n = 0 ;
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
       
        
        button1.setEnabled(false);
        if(!isGeser){
            setDare(1);
            n = 0 ;
            Thread th=new Thread(){
            
            public void run(){
            try{
            for(int i=0;i<=410;i++){
            Thread.sleep(1);
             
             panelGeser.setBounds(i , 0,394 , 445); 
            
            if(i==80){
              //  System.out.println("geser ke kanan");
               lg2.setVisible(true);
               lg.setVisible(false);
                
            }
       
            }
//             panelRound3.revalidate();
//             panelRound3.repaint();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            }

            }
            };th.start();
        
        isGeser = true ;
        button1.setText("Login Sebagai Admin");
        button1.setEnabled(true);
        nStatus = 0 ;
          
        } else {
            setDare(2);
             n = 1;
             nStatus = 1 ;
             Thread th=new Thread(){

            public void run(){
            try{
          
            for(int i=410 ;i>=0;i--){
            Thread.sleep(1);
             panelGeser.setBounds(i , 0,394 , 445);
             
            if(i==380){
              lg2.setVisible(false);
              lg.setVisible(true);
            }

            }
//            panelRound3.revalidate();
//             panelRound3.repaint();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            }

            }
                
            };th.start();
           
           
         isGeser = false ;
         button1.setText("Login Sebagai Guru");
         button1.setEnabled(true);
        }
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINRUN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINRUN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINRUN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINRUN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINRUN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button button1;
    private javax.swing.JLabel jLabel1;
    private test.PanelRound panelGeser;
    private test.PanelRound panelRound1;
    private test.PanelRound panelRound2;
    private test.PanelRound panelRound3;
    private test.PanelRound panelRound4;
    private test.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
