
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QUIZCREATED;

//import CONNECTION.GLOBALCONNECTION;
import COMPONENT.REPOSITORYQUIZ;
import HomeRun.MAINPANEL;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class CREATEQUESTION extends javax.swing.JPanel {

    /**
     * Creates new form CREATEQUESTION
     */
    
    boolean canUpdate = true  ;
    String Guru ;
    
    private void setGuru(String guru)
    {
        Guru = guru ;
    }
    
    private String getGuru(){
        return Guru ;
    }
    
    public boolean isPrivat  = false ;
    private String metodekerja ;
    String getrandom ;
    String titlesoal ;
    MAINPANEL mp ;
    QUIZ qz ;
    String guruQuiz ;
    REPOSITORYQUIZ RQ ;
    public CREATEQUESTION(MAINPANEL mp, REPOSITORYQUIZ RQ ) {
        this.mp = mp ;  
        this.RQ = RQ;
        //this.Guru = guru ;
        setGuru(mp.WhoAmI);
        System.out.println("me is in quiz" +mp.getWhoAmI()); 
        guruQuiz = mp.getWhoAmI();
        initComponents();
        QUIZ qz =new  QUIZ (mp);
        this.qz = qz ;
//        qz.config();
       // con = qz.con;
        
       
        setGuru("Frans");
        sandi.setVisible(false);
        sanditxt.setVisible(false);
    }
    
    
    
     void concatToQuestion(QUIZ qz){
     String metode = "";
     int waktu = 0 ;
     int kelas = 0 ;
     
     
     if(live.isSelected()){
         metode = "Live";
         canUpdate = true ;
     } else if (normal.isSelected()){
         metode = "Normal";
         canUpdate = true ;
     }  else {
         canUpdate = false ;
     }
     
     
     if(menit20.isSelected()){
         waktu = 20 ;
     } else if (menit30.isSelected()){
         waktu = 30 ;
     } else if(menit45.isSelected()){
         waktu = 45 ;
     } else if(menit60.isSelected()){
         waktu = 60 ;
     } else if(menit90.isSelected()){
         waktu = 90 ;
     } else {
         canUpdate = false ;
     }
     
     
     
     
     if(kelas3.isSelected()){
         kelas = 3;
     } else if(kelas4.isSelected()){
         kelas = 4;
     } else if(kelas5.isSelected()){
         kelas = 5;
     } else if(kelas6.isSelected()){
         kelas = 6;
     }  else if(campuran.isSelected()){
         kelas = 7;
     } else {
         canUpdate = false ;
     }
     
     RANDOMNUMBER rd = new RANDOMNUMBER();
     getrandom = rd.getRandom();
  //   String Guru = getGuru();
     String Judul = judul.getText();
     String Keterangan = keterangan.getText();
     String soaltemp = jumlahsoalcmb.getSelectedItem().toString();
     int soal = Integer.parseInt(soaltemp);
     String akses = aksescmb.getSelectedItem().toString();
     String studi = mapel.getSelectedItem().toString();
     qz.set(getrandom ,soal, waktu, kelas, Judul, guruQuiz, metode, akses, studi ,
             Keterangan );
     
     
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kelas3 = new javax.swing.JCheckBox();
        kelas4 = new javax.swing.JCheckBox();
        kelas5 = new javax.swing.JCheckBox();
        kelas6 = new javax.swing.JCheckBox();
        campuran = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        sandi = new javax.swing.JLabel();
        sanditxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        live = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menit20 = new javax.swing.JRadioButton();
        jScrollPane1 = new ScrollBar.ScrollPaneWin11();
        keterangan = new javax.swing.JTextArea();
        menit30 = new javax.swing.JRadioButton();
        menit90 = new javax.swing.JRadioButton();
        menit60 = new javax.swing.JRadioButton();
        menit45 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        myButton1 = new button.MyButton();
        judul = new textfield.TextField();
        aksescmb = new combobox.Combobox();
        jumlahsoalcmb = new combobox.Combobox();
        mapel = new combobox.Combobox();
        myButton2 = new button.MyButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelRound1 = new test.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("JUDUL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("KELAS");

        buttonGroup4.add(kelas3);
        kelas3.setText("3");
        kelas3.setOpaque(false);

        buttonGroup4.add(kelas4);
        kelas4.setText("4");
        kelas4.setOpaque(false);
        kelas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelas4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(kelas5);
        kelas5.setText("5");
        kelas5.setOpaque(false);

        buttonGroup4.add(kelas6);
        kelas6.setText("6");
        kelas6.setOpaque(false);

        buttonGroup4.add(campuran);
        campuran.setText("CAMPURAN");
        campuran.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("AKSES");

        sandi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sandi.setText("KATA SANDI ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("METODE");

        buttonGroup1.add(live);
        live.setText("LIVE QUIZ");
        live.setOpaque(false);

        buttonGroup1.add(normal);
        normal.setText("NORMAL");
        normal.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("BATAS WAKTU");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("KETERANGAN SOAL (OPSIONAL)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("JUMLAH SOAL");

        buttonGroup3.add(menit20);
        menit20.setText("20");
        menit20.setOpaque(false);

        keterangan.setColumns(20);
        keterangan.setRows(5);
        jScrollPane1.setViewportView(keterangan);

        buttonGroup3.add(menit30);
        menit30.setText("30");
        menit30.setOpaque(false);

        buttonGroup3.add(menit90);
        menit90.setText("90");
        menit90.setOpaque(false);

        buttonGroup3.add(menit60);
        menit60.setText("60");
        menit60.setOpaque(false);

        buttonGroup3.add(menit45);
        menit45.setText("45");
        menit45.setOpaque(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("MAPEL");

        jLabel5.setText("Menit");

        myButton1.setText("BUAT QUIZ");
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });

        judul.setBackground(new java.awt.Color(204, 204, 255));
        judul.setLabelText("");
        judul.setLineColor(new java.awt.Color(0, 0, 0));

        aksescmb.setBackground(new java.awt.Color(204, 204, 255));
        aksescmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PUBLIC", "PRIVAT" }));
        aksescmb.setSelectedIndex(-1);
        aksescmb.setLabeText("");

        jumlahsoalcmb.setBackground(new java.awt.Color(204, 204, 255));
        jumlahsoalcmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "10", "15", "20", "30", "50" }));
        jumlahsoalcmb.setSelectedIndex(-1);
        jumlahsoalcmb.setLabeText("");

        mapel.setBackground(new java.awt.Color(204, 204, 255));
        mapel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IPA", "IPS", "BAHASA INDONESIA ", "PPKN ", "BAHASA INGGRIS ", "MATEMATIKA ", "SENI BUDAYA ", "OLAHRAGA", "BAHASA MANDARIN" }));
        mapel.setSelectedIndex(-1);
        mapel.setLabeText("");

        myButton2.setText("KEMBALI");
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(sandi)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(live)
                                                .addGap(18, 18, 18)
                                                .addComponent(normal))
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(kelas3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(kelas4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(kelas5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(kelas6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campuran))
                                            .addComponent(aksescmb, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jumlahsoalcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(mapel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(panelLayout.createSequentialGroup()
                                                    .addComponent(menit20)
                                                    .addGap(2, 2, 2)
                                                    .addComponent(menit30)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(menit45)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(menit60)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(menit90)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(jLabel5)))))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(sanditxt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 146, Short.MAX_VALUE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kelas3)
                            .addComponent(kelas6)
                            .addComponent(kelas5)
                            .addComponent(kelas4)
                            .addComponent(campuran))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aksescmb, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(sandi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sanditxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(live)
                            .addComponent(normal))
                        .addGap(6, 6, 6)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahsoalcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(menit20)
                            .addComponent(menit60)
                            .addComponent(menit90)
                            .addComponent(menit45)
                            .addComponent(menit30)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(24, 24, 24)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("FORMULIR PEMBUATAN QUIZ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive\\Pictures\\murid1.jpg")); // NOI18N

        jLabel13.setText("JUDUL KUIS JUGA DAPAT MEMPENGARUHI");

        jLabel14.setText("KETERTARIKAN MURID LOHHH !!");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel13))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(568, 568, 568))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kelas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelas4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelas4ActionPerformed

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
        buttonGroup3.clearSelection();
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
        
        // 
        titlesoal  = judul.getText();
        int lengthLocal = Integer.parseInt(jumlahsoalcmb.getSelectedItem().toString());
        String sandiku = sandi.getText();
//        QUIZ qz = new QUIZ();
        JOptionPane.showMessageDialog(mp, "are u sure , u is " +guruQuiz);
        concatToQuestion(qz);
   
        if(!isPrivat){
            
            qz.createDB();
            if(qz.isSucces){

                QUIZFILL qf = new QUIZFILL();
                qf.setLengthSoal(lengthLocal);
             // qf.setIDsoal(getrandom);

                QUIZPANEL qp = new QUIZPANEL(qf ,mp);
                qp.setHeader(titlesoal , getGuru());
                qp.setNextRandom(getrandom);

                mp.initParent(qp);
              

               
                


             
                
            } else{
                //System.out.println("gagal");
            }     
        } else if(isPrivat){
            qz.create(sandiku);
        }
    }//GEN-LAST:event_myButton3ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        titlesoal  = judul.getText();
        int lengthLocal = Integer.parseInt(jumlahsoalcmb.getSelectedItem().toString());
        String sandiku = sandi.getText();
//        QUIZ qz = new QUIZ();
        concatToQuestion(qz);
   
        if(!isPrivat){
            qz.createDB();
            if(qz.isSucces){

                QUIZFILL qf = new QUIZFILL();
                qf.setLengthSoal(lengthLocal);
             // qf.setIDsoal(getrandom);

                QUIZPANEL qp = new QUIZPANEL(qf , mp);
                qp.setHeader(titlesoal , getGuru());
                qp.setNextRandom(getrandom);
                mp.initParent(qp);
                
            } else{
                System.out.println("gagal");
            }     
        } else if(isPrivat){
            qz.create(sandiku);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        // TODO add your handling code here:
        mp.initParent(RQ);
    }//GEN-LAST:event_myButton2ActionPerformed
//public void create() {
//        RANDOMNUMBER rd = new RANDOMNUMBER();
//      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//        try {
//            String sql = "insert into soal (Guru , Akses , sistem , idSoal , kelas , jumlahsoal"
//                    + "judul , waktu , keterangan , tanggalbuat) values (?,?,?,?,?,?,?,?,?,curdate()";
//        prs = con.prepareStatement(sql);
//        prs.setString(1, guru);
//        prs.setString(2, akses);
//        prs.setString(3, metode);
//        prs.setString(4, rd.getRandom() );
//        prs.setInt(5, kelas);
//        prs.setInt(7, jumlahsoal);
//        prs.setInt(8, waktu);
//        prs.setString(9, keterangan);
//        
//        int n = prs.executeUpdate();
//        
//        isSucces = n > 0 ? true : false ;
//     
//        } catch (SQLException e) {
//            System.out.println(e.getMessage());
//        }
//    
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private combobox.Combobox aksescmb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox campuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private textfield.TextField judul;
    private combobox.Combobox jumlahsoalcmb;
    private javax.swing.JCheckBox kelas3;
    private javax.swing.JCheckBox kelas4;
    private javax.swing.JCheckBox kelas5;
    private javax.swing.JCheckBox kelas6;
    private javax.swing.JTextArea keterangan;
    private javax.swing.JRadioButton live;
    private combobox.Combobox mapel;
    private javax.swing.JRadioButton menit20;
    private javax.swing.JRadioButton menit30;
    private javax.swing.JRadioButton menit45;
    private javax.swing.JRadioButton menit60;
    private javax.swing.JRadioButton menit90;
    private button.MyButton myButton1;
    private button.MyButton myButton2;
    private javax.swing.JRadioButton normal;
    private javax.swing.JPanel panel;
    private test.PanelRound panelRound1;
    private javax.swing.JLabel sandi;
    private javax.swing.JTextField sanditxt;
    // End of variables declaration//GEN-END:variables
}
