/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COMPONENT;

import HomeRun.LOGINRUN;
import HomeRun.MAINPANEL;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author ACER
 */
public class LOGINPANEL extends javax.swing.JPanel {

    /**
     * Creates new form LOGINPANEL
     */
    LOGINRUN lr ;
    private ResultSet rs ;
    private Connection con ;
    private PreparedStatement prs ;
    private login lg ;
    signup sg ;
    private String code ;
    private boolean meSignUp = false ;
    public LOGINPANEL(LOGINRUN lr) {
        initComponents();
        this.con = lr.con ;
        this.lr = lr ;
        login lgw = new login();
        this.lg = lgw ;
        ChangeComponent(lg);
        jLabel3.setText("<HTML><u>Daftar Akun</u></HTML>");
    }
   
    public void ChangeComponent(Component cmp){
        jPanel1.removeAll();
        jPanel1.add(cmp);
        jPanel1.repaint();
        jPanel1.revalidate();
    }
   
    public void NoChanges(){
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }
    
    public void setTitle(String s){
        jLabel1.setText(s);
    }
    
    private boolean isSucces ; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new test.PanelRound();
        button2 = new button.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelRound1.setBackground(new java.awt.Color(204, 204, 204));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button2.setBackground(new java.awt.Color(102, 153, 255));
        button2.setText("MASUK");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        panelRound1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 106, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("GURU LOGIN");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 24));

        jLabel2.setText("Belum punya Akun ? ");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        jPanel1.setLayout(new java.awt.CardLayout());
        panelRound1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 237, 211));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    boolean isDaftar = false ;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if(!isDaftar){
            signup sg1 = new signup();
            this.sg = sg1;
            ChangeComponent(sg);
            isDaftar = true;
            jLabel2.setVisible(false);
            jLabel3.setText("Login");
            button2.setText("DAFTAR");
            meSignUp = true ;
        } else {
            login lg1 = new login();
            this.lg = lg1;
            ChangeComponent(lg);
            isDaftar = false;
            jLabel2.setVisible(true);
            jLabel3.setText("Daftar");
            button2.setText("MASUK");
            meSignUp = false ;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void addAccount(){
        String sql = "INSERT INTO admin(kodePegawai , username , password , status) VALUES (?,?,? ,?)";
        try{
            prs =con.prepareStatement(sql);
            prs.setString(1, code);
            prs.setString(2, sg.getStaffName());
            prs.setString(3, sg.getStaffPassword());
            prs.setString(4, "Guru");
            int n = prs.executeUpdate();
            if(n > 0){
                System.out.println("Inserted Data " );
                ChangeComponent(lg);
            } else {
                System.out.println("can not inserted data ");
            }
        } catch(SQLException e){
            System.out.println("err "+e.getMessage());
        }
    }
    
    private void SignUp(){
        String sql = "SELECT * FROM pegawai WHERE kodePegawai = ? AND status ='Guru' ";
        try{
            prs = con.prepareStatement(sql);
            prs.setString(1, sg.getCodeStaff());
            rs = prs.executeQuery();
            if(rs.next()){
                code = sg.getCodeStaff();
                isSucces = true ;
            } else {
                System.out.println("Can not get Data");
            }
        } catch(SQLException e){
            System.out.println("err " +e.getMessage());
        }
    }
    
    private void getLogin(String s){
        String sql = " SELECT * FROM admin WHERE username = ? AND password = ? and Status = ?";
        try {
            prs = con.prepareStatement(sql);
            prs.setString(1, lg.getUsername());
            String who = lg.getUsername();
            System.out.println("username => " +lg.getUsername());
            prs.setString(2, lg.getPassowrd());
            prs.setString(3, s);
            System.out.println("status " +s);
            System.out.println("pass => " +lg.getPassowrd());
            rs = prs.executeQuery();
            while(rs.next()){
                System.out.println("Succes LOGIN");
//                String Status = rs.getString(3) ;
                String kodep = rs.getString(4);
                MAINPANEL mp = new MAINPANEL(who , s ,kodep);
                
//                mp.setWhoMeString(lg.getUsername());
                mp.setVisible(true);
                lr.dispose();
            }
        } catch (SQLException e) {
              System.out.println("err => " +e.getMessage());
        }
    }
    
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(isDaftar){
            SignUp();
            if(isSucces){
                addAccount();
                login lg1 = new login();
            this.lg = lg1;
            ChangeComponent(lg);
            isDaftar = false;
            jLabel2.setVisible(true);
            jLabel3.setText("Daftar");
            button2.setText("MASUK");
            meSignUp = false ;
            }
        } else {
//               System.out.println("ha");
               if(lr.getDare()==1){
                   //  System.out.println("Saya Adalah Guru");
                     getLogin("Guru");
                     System.out.println("status Guru");
                     
               } else if(lr.getDare()==2){
                  // System.out.println("Saya adalah Admin");
                    getLogin("Admin");
                       System.out.println("status Admin");
               }
        }
        
    }//GEN-LAST:event_button2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private test.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
