/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COMPONENT;

import HomeRun.MAINPANEL;
import java.awt.Color;
import java.util.Random;

/**
 *
 * @author ACER
 */
public class MYSTUDY extends javax.swing.JPanel {

    /**
     * Creates new form MYSTUDY
     */
    MAINPANEL mp ;
    private String kodeSoal ;
    public String WhoFromHere;
    public  void setKodeSoal(String kode){
        kodeSoal = kode ;
    }
    
    private void alsoColor(){
        Random random = new Random();
        int randomNumber = random.nextInt(12) + 1;
        
        if(randomNumber==1){
            panelRound1.setBackground(Color.yellow);
        } else  if(randomNumber==2){
            panelRound1.setBackground(Color.red);
        } else  if(randomNumber==3){
            panelRound1.setBackground(Color.blue);
        } else  if(randomNumber==4){
            panelRound1.setBackground(Color.green);
        } else  if(randomNumber==5){
            panelRound1.setBackground(Color.GRAY);
        } else  if(randomNumber==6){
            panelRound1.setBackground(Color.CYAN);
        } else  if(randomNumber==7){
            panelRound1.setBackground(Color.DARK_GRAY);
        } else  if(randomNumber==8){
            panelRound1.setBackground(Color.MAGENTA);
        } else  if(randomNumber==9){
            panelRound1.setBackground(Color.PINK);
        }
    }
    private  String getKodeSoal(){
        return kodeSoal ;
    }
    public MYSTUDY(MAINPANEL mp) {
        initComponents();
        alsoColor();
        this.mp = mp ;
    }
    
    public void initThis(String s , String classRoom)
    {
        namaMapel.setText(s);
        namaKelas.setText(classRoom);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new test.PanelRound();
        namaMapel = new javax.swing.JLabel();
        namaKelas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelRound1.setBackground(new java.awt.Color(0, 153, 102));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound1MouseClicked(evt);
            }
        });
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaMapel.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        namaMapel.setForeground(new java.awt.Color(255, 255, 255));
        namaMapel.setText("NAMA MAPEL");
        panelRound1.add(namaMapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 251, -1));

        namaKelas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        namaKelas.setForeground(new java.awt.Color(255, 255, 255));
        namaKelas.setText("KELAS");
        panelRound1.add(namaKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\OneDrive\\Pictures\\tes-removebg-preview.png")); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 210, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelRound1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound1MouseClicked
        // TODO add your handling code here:
        EACHSTUDYPANEL esp = new EACHSTUDYPANEL(mp, getKodeSoal());
        esp.initHeader(namaMapel.getText(), namaKelas.getText());
        esp.setTheTeacher(WhoFromHere);
        mp.initParent(esp);
    }//GEN-LAST:event_panelRound1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namaKelas;
    private javax.swing.JLabel namaMapel;
    public static test.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
