/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package COMPONENT;

/**
 *
 * @author ACER
 */
public class signup extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public signup() {
        initComponents();
    }

    public String getCodeStaff(){
        return textField1.getText();
    }
    
    public String getStaffName(){
        return username.getText();
    }
    
    public String getStaffPassword(){
        return kataSandi.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kataSandi = new textfield.PasswordField();
        textField1 = new textfield.TextField();
        username = new textfield.TextField();

        setBackground(new java.awt.Color(204, 204, 204));

        kataSandi.setBackground(new java.awt.Color(204, 204, 204));
        kataSandi.setLabelText("Kata Sandi");
        kataSandi.setShowAndHide(true);

        textField1.setBackground(new java.awt.Color(204, 204, 204));
        textField1.setLabelText("Kode Pegawai");

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setLabelText("Username");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kataSandi, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
            .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(kataSandi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private textfield.PasswordField kataSandi;
    private textfield.TextField textField1;
    private textfield.TextField username;
    // End of variables declaration//GEN-END:variables
}
